/**
 * This code was generated by Builder.io.
 */
import React from 'react'

export default function CampingFeatures() {
  const features = [
    {
      icon: 'https://cdn.builder.io/api/v1/image/assets/TEMP/7e9bb68388691c3855b9a6d24016bf7fda07cf7350970456824ed38ccf26dedb?placeholderIfAbsent=true&apiKey=917a01bb4dc8469db872546ae2709b5f',
      label: '親子設施',
    },
    {
      icon: 'https://cdn.builder.io/api/v1/image/assets/TEMP/7e9bb68388691c3855b9a6d24016bf7fda07cf7350970456824ed38ccf26dedb?placeholderIfAbsent=true&apiKey=917a01bb4dc8469db872546ae2709b5f',
      label: '洗衣機',
    },
    {
      icon: 'https://cdn.builder.io/api/v1/image/assets/TEMP/7e9bb68388691c3855b9a6d24016bf7fda07cf7350970456824ed38ccf26dedb?placeholderIfAbsent=true&apiKey=917a01bb4dc8469db872546ae2709b5f',
      label: '接送服務',
    },
    {
      icon: 'https://cdn.builder.io/api/v1/image/assets/TEMP/7e9bb68388691c3855b9a6d24016bf7fda07cf7350970456824ed38ccf26dedb?placeholderIfAbsent=true&apiKey=917a01bb4dc8469db872546ae2709b5f',
      label: '無障礙',
    },
    {
      icon: 'https://cdn.builder.io/api/v1/image/assets/TEMP/7e9bb68388691c3855b9a6d24016bf7fda07cf7350970456824ed38ccf26dedb?placeholderIfAbsent=true&apiKey=917a01bb4dc8469db872546ae2709b5f',
      label: '攜帶寵物',
    },
    {
      icon: 'https://cdn.builder.io/api/v1/image/assets/TEMP/ec672f5f1e9e17466a138ba900b4f8c839d7b3b166bd9aa25c0cafe5dcb490bb?placeholderIfAbsent=true&apiKey=917a01bb4dc8469db872546ae2709b5f',
      label: '野餐桌',
    },
    {
      icon: 'https://cdn.builder.io/api/v1/image/assets/TEMP/7e9bb68388691c3855b9a6d24016bf7fda07cf7350970456824ed38ccf26dedb?placeholderIfAbsent=true&apiKey=917a01bb4dc8469db872546ae2709b5f',
      label: '供應熱水',
    },
    {
      icon: 'https://cdn.builder.io/api/v1/image/assets/TEMP/ec672f5f1e9e17466a138ba900b4f8c839d7b3b166bd9aa25c0cafe5dcb490bb?placeholderIfAbsent=true&apiKey=917a01bb4dc8469db872546ae2709b5f',
      label: '餐廳',
    },
    {
      icon: 'https://cdn.builder.io/api/v1/image/assets/TEMP/7e9bb68388691c3855b9a6d24016bf7fda07cf7350970456824ed38ccf26dedb?placeholderIfAbsent=true&apiKey=917a01bb4dc8469db872546ae2709b5f',
      label: '公共衛浴',
    },
  ]

  return (
    <div className="ecamping-features">
      {features.map((feature, index) => (
        <div key={index} className="efeature-item">
          <img src={feature.icon} alt="" className="efeature-icon" />
          <span className="efeature-label">{feature.label}</span>
        </div>
      ))}
      <style jsx>{`
        .ecamping-features {
          background-color: #fffabb;
          border-radius: 20px;
          color: #000;
          display: flex;
          flex-wrap: wrap;
          font-family: Zen Maru Gothic, sans-serif;
          gap: 17px 40px;
          margin: auto 0;
          padding: 15px;
          width: 500px;
        }
        .efeature-item {
          align-items: center;
          display: flex;
          gap: 13px;
          width: 114px;
        }
        .efeature-icon {
          aspect-ratio: 1;
          height: 33px;
          object-fit: contain;
          width: 33px;
        }
      `}</style>
    </div>
  )
}
